### PR TITLE
Add central config

### PR DESCRIPTION
**Pull request by chiahaoliu**
explicitly load python object from corresponding files.

This provides a solution to ambiguity of B_DIR, pe1c... between simulation and real XPD environment

### CODE REVIEW

**Comment by chiahaoliu** [comment]
This is just for sharing idea.
Other imports under `xpdacq` should be cleaned too, once basic idea of this pull request passes review.

**Comment by sbillinge** [comment]
I need to see it tested to know if it will work.  The possibly simpler
thing is just to sequence things in the right order.  We have all our
import statements at the top of the file  in 999-load of (Python
convention) but in this startup file things get started in the order they
appear in the file sequence, so imports that presume something exists
should happen after that thing is created....it may just be that we have to
carefully sequence things.

On Thursday, February 18, 2016, Timothy Liu <notifications@github.com>
wrote:

> This is just for sharing idea.
> Other imports under xpdacq should be cleaned too, once basic idea of this
> pull request passes review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/85#issuecomment-185923142>.
>


-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
Yes, we can test together and see if it works as we expect.

Regarding the loading sequence. Up to `999-loadxpd.py`, everything, including `pe1c` `cs700`..., has been created. We can properly import objects we need in `999-loadxpd.py` but two things we wanted to do (and haven't been able to ) are:
  1. a robust way to differentiate simulation and real experiment so that we can at least centralize `B_DIR`
  2. hence "hand" objects  accordingly to `xpdacq`, depends on whether we are in simulation or not.

My idea was to keep these logics inside `xpdacq`, not the startup file, so that we have better version control( it might be even possible to have single `999-load.py` for both simulation and real experiment).

For bullet point 2, problem we have now is that objects we need exist in naming space defined by files inside `startup/` directory, not the naming space used in `xpdacq` packages. We have to pass required objects to `xpdacq`, either by `get_ipython` methond or direct import from source file. From discussion in #18, `get_ipython` method has been thought to be less ideal since user needs to manually import modules after ipython session has been created. And direct import from `999-loadxpd.py` might be more tricky as `ipython profile` directory is system dependent.

Above are just my motivations behind, I am not sure if it is the best approach. I will demonstrate/test this,  once we get chance.

**Comment by sbillinge** [comment]
These are good thoughts.  It would be great to solve this problem.  We
would need a way to "find" the relevant config files I guess, though since
people are copy pasting files into startup anyway we could do that.
Hopefully sthg like this will work.

On Thursday, February 18, 2016, Timothy Liu <notifications@github.com>
wrote:

> Yes, we can test together and see if it works as we expect.
>
> Regarding the loading sequence. Up to 999-loadxpd.py, everything,
> including pe1c cs700..., has been created. We can properly import objects
> we need in 999-loadxpd.py but two things we wanted to do (and haven't
> been able to ) are:
>
>    1. a robust way to differentiate simulation and real experiment so
>    that we can at least centralize B_DIR
>    2. hence "hand" objects accordingly to xpdacq, depends on whether we
>    are in simulation or not.
>
> My idea was to keep these logics inside xpdacq, not the startup file, so
> that we have better version control( it might be even possible to have
> single 999-load.py for both simulation and real experiment).
>
> For bullet point 2, problem we have now is that objects we need exist in
> naming space defined by files inside startup/ directory, not the naming
> space used in xpdacq packages. We have to pass required objects to xpdacq,
> either by get_ipython methond or direct import from source file. From
> discussion in #18 <https://github.com/xpdAcq/xpdAcq/issues/18>,
> get_ipython method has been thought to be less ideal since user needs to
> manually import modules after ipython session has been created. And direct
> import from 999-loadxpd.py might be more tricky as ipython profile
> directory is system dependent.
>
> Above are just my motivations behind, I am not sure if it is the best
> approach. I will demonstrate/test this, once we get chance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/85#issuecomment-185986507>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
This branch is too far from current approach after discussing with Tom. So I will abandon it and close this pull request.

**Pull request closed without merging**
