### PR TITLE
Xpd computer_0326

### PR DESCRIPTION
**Pull request by chiahaoliu**
This is to share changes/fixes done at XPD on 20160322.

New logic of scans are tested, wrapper on run_engine paused state is added and other small bugs related to outdated `sc_params` have been cleaned in package.

Commit history looks horrible as I pull it directly but not rebase ( I could have done). But this code works fine at XPD now.

### CODE REVIEW

**Comment by sbillinge** [comment]
@chiahaoliu these are mostly hotfixes.  Do we want to pull them all in, or do many of them have proper fixes in other pull requests?

**Comment by chiahaoliu** [comment]
Sorry, I thought my reply was sent but it actually sits in my cache forever...

This PR is for reference and only the last three commits are effectively used, which are light edits on remaining effects due to changing `Scan` to `ScanPlan` across modules. I will open another one to cheery-pick commits used in this PR, so that we have a clean and easy to understand history.

**Comment by sbillinge** [comment]
great, thanks so much.

S

On Mon, Mar 28, 2016 at 11:15 AM, Timothy Liu <notifications@github.com>
wrote:

> Sorry, I thought my reply was sent but it actually sits in my cache
> forever...
>
> This PR is for reference and only the last three commits are effectively
> used, which are light edits on remaining effects due to changing Scan to
> ScanPlan across modules. I will open another one to cheery-pick commits
> used in this PR, so that we have a clean and easy to understand history.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/158#issuecomment-202432985>
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
effective commits are cherry-picked to other PR. Close for now.

**Pull request closed without merging**
