### PR TITLE
Sbillinge test mock

### PR DESCRIPTION
**Pull request by chiahaoliu**
This is the work from @sbillinge. I open this pull request just to avoid manually pushing branch to upstream repo. Only minor conflicts exist in `xpdacq.py` and they have been resolved. `Unittest` in `test_validatedark.py` remains successful.

### CODE REVIEW

**Comment by chiahaoliu** [comment]
I can pull it in if everything still looks good in this pull request

**Comment by sbillinge** [comment]
The edits look good but it can't be pulled in cos of conflicts?

**Comment by sbillinge** [comment]
@chiahaoliu go ahead and fix the conflicts then pull it in

**Comment by chiahaoliu** [comment]
Just fixed conflicts and I am pulling in right now

**Pull request merged**
