### PR TITLE
ENH: composition string parser

### PR DESCRIPTION
**Pull request by chiahaoliu**
Revisit parser for excel spreadsheet. Now it generates strings that `pdfgetX3` consumes

Also, add tests for `import_sample`

Code is ready to be reviewed.

### CODE REVIEW

**Comment by tacaswell** [comment]
Probably do not want to commit `.DSStore`

**Comment by chiahaoliu** [comment]
@CJ-Wright can you take a look at the Travis build? 

It seems that comes from ``LiveTable`` and ``Matplotlib``?

**Comment by CJ-Wright** [comment]
@chiahaoliu The error is coming from the mpl build from conda.
put this into the travis.yml right below `before_install` but before the DB definitions. Replace everything in between
```
  - git clone https://github.com/NSLS-II/nsls2-ci --branch master --single-branch ~/ci_scripts
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda update conda --yes
  - export CONDARC=ci/condarc```

**Comment by chiahaoliu** [comment]
replaced by #359

**Pull request closed without merging**
