### PR TITLE
Simon test git workflow

### PR DESCRIPTION
**Pull request by sbillinge**
These are just tiny edits to the installation script, but I wanted to go step by step through the entire workflow (Thanks @tacaswell ) to make sure that I understood it, and that I could make it work....also to see how it appears in the github desktop client that I sometimes use.

No need to comment on this....

### CODE REVIEW

**Comment by tacaswell** [comment]
One of the critical rules of the PR based workflow is that you do not merge your own PRs :wink:

**Comment by sbillinge** [comment]
Haha, I know!  But my testing would have been very slowed down in this case
😆

Everything worked great except I am still a tad unsure how to update my
fork to synchronize with xpdacq after I merge the pull request into
XPD/master.

On Friday, February 12, 2016, Thomas A Caswell <notifications@github.com>
wrote:

> One of the critical rules of the PR based workflow is that you do not
> merge your own PRs [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/53#issuecomment-183347187>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by tacaswell** [comment]
The best way to do this is to have multiple remotes on your local checkout

```
09:29 $ git remote -v
chiahaoliu      git://github.com/chiahaoliu/xpdAcq.git (fetch)
chiahaoliu      git://github.com/chiahaoliu/xpdAcq.git (push)
tacaswell       git@github.com:tacaswell/xpdAcq.git (fetch)
tacaswell       git@github.com:tacaswell/xpdAcq.git (push)
xpdAcq  git://github.com/xpdAcq/xpdAcq.git (fetch)
xpdAcq  git://github.com/xpdAcq/xpdAcq.git (push)
```

So I would do

```
git checkout master
git remote update
git merge --ff-only xpdAcq/master
# and if I care about keeping 'master' on my fork up-to-date (which I normally do not)
git push tacaswell master
```

**Comment by tacaswell** [comment]
See the first two sections of https://scikit-beam.github.io/scikit-beam/resource/dev_guide/index.html

**Comment by sbillinge** [comment]
You mean I should read the documentation? 😉

On Friday, February 12, 2016, Thomas A Caswell <notifications@github.com>
wrote:

> See the first two sections of
> https://scikit-beam.github.io/scikit-beam/resource/dev_guide/index.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/53#issuecomment-183352873>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Pull request merged**
