### PR TITLE
ENH: Filter positions in metadata

### PR DESCRIPTION
**Pull request by eaculb**
Closes https://github.com/xpdAcq/mission-control/issues/81

### CODE REVIEW

**Comment by eaculb** [comment]
Needs a simulated filter bank to pass the build.

**Comment by CJ-Wright** [comment]
The code you are looking for is in https://github.com/xpdAcq/xpdSim/pull/25#pullrequestreview-50146524 ish. It needs some cleaning.

**Comment by CJ-Wright** [comment]
Seems like there's an issue with the `xpd_configuration` https://travis-ci.org/xpdAcq/xpdAcq/jobs/327473099#L1062

**Comment by chiahaoliu** [comment]
:+1:

**Comment by chiahaoliu** [comment]
just a tiny point, do we want to rename ``filter_positions`` to ``filter_bank``? Cuz this reflects that fact, it's a ``device`` and aligns with ``fb`` which is the class name.

**Comment by eaculb** [comment]
Good point. I can do this. Now that this is merged and closed can I just push another commit or will it need a new PR?

**Pull request merged**
