### PR TITLE
Prf only do dark lookup once

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
@chiahaoliu How do I run the tests?

**Comment by chiahaoliu** [comment]
Thanks Tom! Usually for functionality interacts with `databroker`, I have to go on notebook server and play with real data. My dumb way of doing it is to paste modified code, replacing saving functionality with print statements (I should have made a dryrun option) and run it. In `xpdAcq/tests/analysis_functional_tests.py` I have included three headers with edge cases to test modified code.

I just did my dumb test and it verifies your smart approach ;) Let me know if you want to add anything, otherwise I am pretty happy to pull it in.

**Comment by tacaswell** [comment]
I am done.

Is it noticeably faster?  Do you agree this is more readable?

**Comment by sbillinge** [comment]
we have also been running unit tests by going to the tests directory and
using py.test, but because of our struggles at mocking (which are almost
over by the way) we don't have working unit tests for many things inside
xpdacq.py yet.

btw, do you have nice scripts for cleaning up the whitespaces and doing the
pep8 compliance, or that is done by hand?

S


On Wed, Mar 16, 2016 at 2:35 PM, Timothy Liu <notifications@github.com>
wrote:

> Thanks Tom! Usually for functionality interacts with databroker, I have
> to go on notebook server and play with real data. My dumb way of doing it
> is to paste modified code, replacing saving functionality with print
> statements (I should have made a dryrun option) and run it. In
> xpdAcq/tests/analysis_functional_tests.py I have included three headers
> with edge cases to test modified code.
>
> I just did my dumb test and it verifies your smart approach ;) Let me know
> if you want to add anything, otherwise I am pretty happy to pull it in.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/139#issuecomment-197477143>
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by tacaswell** [comment]
I have my editor to strip trailing whitespace on save.  I also have a linter set up so I get highlighting in the editor. 

The rest I do by hand (more-or-less as I read).  There are scripts that will auto-pep8 but I do not trust them (they have broken mpl before).

**Comment by chiahaoliu** [comment]
@tacaswell  it's 0.8 s faster in my test. I will pull in now

**Pull request merged**
