### PR TITLE
0226 dark subtraction

### PR DESCRIPTION
**Pull request by chiahaoliu**
first trial of dark subtraction

Codes turn to be super long for this functionality as a few exceptions should be captured. Logic could possibly be better for a robust code.

unittest to this functionality will be actively updated in this pull request.

### CODE REVIEW

**Comment by chiahaoliu** [comment]
Yes, I understood the logic but I came out with slightly different logic when I was trying to realize it. Let me explain my reasonings and see if we some of them make sense.

- basica workflow:
  - after every `dark`, I dump a light weight `dark_<timestamp>.yaml into `dark_base`
  - every `prun`, I pull dark yamls inside `dark_base` that lie within `expire_time` based on `modification time` and read all of them into a list object
  - I interact with that list object and find out right dark. If there is already one, return the `uid`, otherwise return `None` and this will trigger another `dark` which dump another yaml inside `dark_base`
  - metadata of `prun` get updated and `dark_field_uid` is included.
  - When save the data, the same logic of `analyze()` mentioned before is used.

So why do I want to take modification time instead of timestamp?
  - I found this might be the lightest way to obtain the timestamp at the end of dark run, assume the latency of writing is negligible. The reason why I need to have timestamp at the end of dark run is following. I justify if dark is the right one based on comparing the time information of this dark with current time. Currently the time information of dark is collected *at the beginning* of this dark scan so once I have a `exposure_time` longer than `expire_time`, it will always lead to a dark scan since I don't compare the end of `dark` with the beginning of `prun`. 

Up to this moment, I already realized your `dark_list` is a better approach as long as I record timestamp by the end of dark scan..... I will try it now :)

**Comment by sbillinge** [comment]
I see, sorry I didn't understand.  I think that is a reasonable design.  We
should think which is more robust and easier to maintain.

For the time stamp, why not just request the current time in prun after
control is returned from RE.  Would that work?

S

On Sunday, February 28, 2016, Timothy Liu <notifications@github.com> wrote:

> Yes, I understood the logic but I came out with slightly different logic
> when I was trying to realize it. Let me explain my reasonings and see if we
> some of them make sense.
>
>    - basica workflow:
>       - after every dark, I dump a light weight dark_<timestamp>.yaml into
>       dark_base`
>       - every prun, I pull dark yamls inside dark_base that lie within
>       expire_time based on modification time and read all of them into a
>       list object
>       - I interact with that list object and find out right dark. If
>       there is already one, return the uid, otherwise return None and
>       this will trigger another dark which dump another yaml inside
>       dark_base
>       - metadata of prun get updated and dark_field_uid is included.
>       - When save the data, the same logic of analyze() mentioned before
>       is used.
>
> So why do I want to take modification time instead of timestamp?
>
>    - I found this might be the lightest way to obtain the timestamp at
>    the end of dark run, assume the latency of writing is negligible. The
>    reason why I need to have timestamp at the end of dark run is following. I
>    justify if dark is the right one based on comparing the time information of
>    this dark with current time. Currently the time information of dark is
>    collected *at the beginning* of this dark scan so once I have a
>    exposure_time longer than expire_time, it will always lead to a dark
>    scan since I don't compare the end of dark with the beginning of prun.
>
> Up to this moment, I already realized your dark_list is a better approach
> as long as I record timestamp by the end of dark scan..... I will try it
> now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/98#issuecomment-189902389>.
>


-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
yes, use time stamp at the end of `dark` is the approach I am taking and this approach should solve the problem I mentioned.

**Comment by chiahaoliu** [comment]
Thanks! I modified my code and make it pass a new `unittest` on updating metadata

**Comment by chiahaoliu** [comment]
I update my dark subtraction logic and now the code pass all unittests calling exactly the same function in production code. But now there are conflicts ... :(

**Comment by sbillinge** [comment]
Do you need help with the conflicts?  The only change to that file should
have been to remove the if statement.  Most of the changes would have been
in the testing method.  Right?

On Monday, February 29, 2016, Timothy Liu <notifications@github.com> wrote:

> I update my dark subtraction logic and now the code pass all unittests
> calling exactly the same function in production code. But now there are
> conflicts ... :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/98#issuecomment-190426910>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
I think the origin of this conflict is originated from my last commit, which arrived later than the time I merged the latest pull request and the git history is now diverged. There is a guide on merging this pull request by command line, but I am not sure if that should be done by me.

**Comment by tacaswell** [comment]
@chiahaoliu I suggest you rebase.

```
git remote update
git checkout 0226_dark_subtraction
git rebase -i upstream/master
# follow directions on screen, resolve conflicts
gitk  # check your work
git push --force chiahaoliu/0226_dark_subtraction
```

**Comment by chiahaoliu** [comment]
@tacaswell 
Thanks, that works magically !

**Pull request merged**
