### PR TITLE
Work glbl config

### PR DESCRIPTION
**Pull request by chiahaoliu**
Because of rebase, commits belonging to pull request #98 are shown here at this time. Production commits are those after commit `fd01e7a`.

### CODE REVIEW

**Comment by sbillinge** [comment]
I checked this out but it doesn't seem to be passing its tests (errors in test_beamtimeSetup)

**Comment by tacaswell** [comment]
```python
if __name__ == '__main__':
```

Is a python language feature https://docs.python.org/3/library/__main__.html

**Comment by sbillinge** [comment]
I get that.  But by using this trick in the ipython context, does it make the module namespace share the namespace of the main ipython session....is that the point?

**Comment by sbillinge** [comment]
@chiahaoliu this still seems to be failing test_beamtimeSetup tests with import errors.

**Comment by chiahaoliu** [comment]
May I know the error? I was awared that there are known issues coming from ipython profile, but I forgot to discuss with you before you left.

**Comment by sbillinge** [comment]
cannot import name AREA_DET

On Tue, Mar 1, 2016 at 10:28 PM, Timothy Liu <notifications@github.com>
wrote:

> May I know the error? I was awared that there are known issues coming from
> ipython profile, but I forgot to discuss with you before you left.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/101#issuecomment-191037338>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
Yes, that is the error I should have mentioned. The main idea of this `global` trick is that `AREA_DET` and other objects are created when profile are loaded. Using `py.test` might not be able to capture this ipython profile behavior properly. I can try to make objects in `setup` section, but this might again mean we are not testing the production code.

**Comment by tacaswell** [comment]
A good practice is to default values to `None`.  That way the names exist and you can check if they are set via `is None`.

**Comment by chiahaoliu** [comment]
do you mean to set default value of object to `None` and selectively import objects depending on values?

**Comment by tacaswell** [comment]
No, just check them for being not-`None` before using them.

**Comment by chiahaoliu** [comment]
I think I might misunderstand some parts of `global` method. I will ask you tomorrow if you will be in @tacaswell

**Comment by chiahaoliu** [comment]
replace with #105. Most updated one

**Pull request closed without merging**
