### PR TITLE
Refactor yaml saving and retrieval

### PR DESCRIPTION
**Pull request by sbillinge**
This is my branch for making the bt.list() function return an immutable list (i.e., elements do not change place with time.)

Right now it is just preliminaries, like a function for stripping and removing internal white-spaces from names that will be used as yaml file-names.  More to come soon.

Also, slightly unrelated, but I wanted a _graceful_exit() function that we can use to jump out of situations without scaring users with a RuntimeError stack dump.  For now it does a slightly cleaner sys.exit with a small error message....less scary than RuntimeError....but could still be nicer.

this is in xpdacq.utils.py where we could put other things that are of broader utility.

### CODE REVIEW

**Comment by sbillinge** [comment]
@chiahaoliu I have finished refactoring the way that the yaml files are contained in a list so that they will not change position in the list randomly.  I am ready for you to test the code and then pull it in.  It is passing all tests right now.

A better design would be to separate the yamling out completely so that when we move away from yaml to a better database solution it won't be so bad to do, but it was a fight to get this going so I don't have the heart to refactor it at this point!  It is better than the code that is working at XPD right now.

**Comment by chiahaoliu** [comment]
Thanks! I am pulling in right now. Also I found there are some parts of code needed to modified since we have new `glbl` structure. I can clean them if you think that is a good timing to do it now.

**Comment by sbillinge** [comment]
do you mean parts in my commits, or parts in other parts of the code?  I do think that it would be good to make it all consistent.  It was a big fight for me to get everything working with the globals, so getting rid of the old legacy code in this respect would be good.

**Comment by chiahaoliu** [comment]
I meant the other part of the code, mainly related to how objects are created in the `xpdacq.py`. I will do the cleaning then.

**Comment by sbillinge** [comment]
awesome....yes please clean.  Also start making test-code to test the
cleans.  I don't see too much test code in your other pull request, or did
I miss it?

Thanks,

S

On Sat, Feb 27, 2016 at 11:34 PM, Timothy Liu <notifications@github.com>
wrote:

> I meant the other part of the code, mainly related to how objects are
> created in the xpdacq.py. I will do the cleaning then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/pull/97#issuecomment-189782771>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Pull request merged**
